# ===============================
# SERVER CONFIGURATION
# ===============================
# The port where your API will run
server.port=8080
spring.application.name=rentManagementSystem

# ===========================================================================================================================================================
# DATABASE CONFIGURATION (Supabase Shared Pooler IPv4)
# ===========================================================================================================================================================
# Replace the host with the exact one from your dashboard, keep port 6543 and the threshold parameter
spring.datasource.url=${DB_URL}

# The username format is postgres.[PROJECT_REF]
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# ===========================================================================================================================================================
# JPA / HIBERNATE CONFIGURATION
# ===========================================================================================================================================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ===============================
# JWT CONFIGURATION (Maps to @Value tags in JwtUtil)
# ===============================
# Must be at least 256-bit (32 characters) for the HS256 algorithm
jwt.secret=1liB8uMAKLe4FXtfuXOM++9bdbWNNkJdyuBplbap61Q=
app.jwt.secret=1liB8uLAXMI4FXtfuXOM++9bdbWNNkJdyuBplbap61Q=
# Token validity in milliseconds (86400000 = 24 hours)
jwt.expiration=86400000
app.jwt.expiration-ms=86400000